spring.application.name=text-to-speech-backend

server.port=8080

# AWS Credentials (use env vars or IAM role in production)
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

# logging.level.org.springframework=DEBUG

# Rate Limit
rate-limit.capacity=${RATE_LIMIT_CAPACITY:5}
rate-limit.refill-tokens=${RATE_LIMIT_REFILL_TOKENS:5}
rate-limit.refill-duration-minutes=${RATE_LIMIT_REFILL_DURATION_MINUTES:1}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/speakit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# 24 hours
jwt.expiration=${JWT_EXPIRATION:86400000}